### ISSUE TITLE
Lack of SHA-1 support

### ISSUE THREAD

**Issue by PhoenixFlame101** [acmpesuecc/quickhash#1]
## The Problem

quickhash doesn't have support for SHA-1 algorithm, any PR that might close this issue should implement these algorithms the same way SHA-256 and MD5 are implemented. While it is cryptographically broken, it is still useful for legacy interoperability purposes.

## Possible Solutions

There's a crate `sha1` contains the SHA-1 alg already implemented. Solving this issue requires you to use this crate and add SHA-1 to the menu.  Make sure the algorithm function is in `algorithm.rs`

## Expected output

If you want to confirm that the algorithm works correctly, you can check against this checksum:

    cargo run NOTICE
    The expected SHA-1 output should be: 2cdae58602dd8b1734bfd2c462dee6497ac28872

---
 - Block time: 30 mins (You need to give updates every 30 mins if you have been assigned)
 - Bounty points: 30

**Comment by BhaviniMadhuranath** [comment]
can i work on this?

**Comment by BhaviniMadhuranath** [comment]
i'm having some difficulty in running the file to check
it's taking some time

**Comment by NavinShrinivas** [comment]
Ok, you have 30 mins to show some progress, All the best!

**Comment by BhaviniMadhuranath** [comment]
i have written some code. i'm unable to run it due to (what i'm guessing is) installation issues

**Comment by PhoenixFlame101** [comment]
If you have rust installed, you can run the program using `cargo run <filename>`, for example `cargo run NOTICE`

**Comment by BhaviniMadhuranath** [comment]
so i checked my installation.. even the path is set. I'm still getting cargo is unrecognised

**Comment by cubed-guy** [comment]
Can I get assigned to this issue
PES2UG21CS477 Sanket Padhi

**Comment by abhiraj2** [comment]
I'll be working on this
