### ISSUE TITLE
Validation of a checksum provided as a command line option

### ISSUE THREAD

**Issue by PhoenixFlame101** [acmpesuecc/quickhash#3]
## The Problem

Currently, the program only calculates a checksum, and does not check if it matches a certain provided checksum.

## Possible Solutions

The best solution is to add a CLI option `--checksum` followed by the checksum to be validated against. The final command should be similar to this:

    cargo run FILEPATH --checksum 2012b030c3f01589c399da291c57d803

The output should say the result of the validation, followed by the file's checksum if it does not match the one provided as an argument.

---
 - Block time: 15 mins
 - Bounty points: 20

**Comment by abhiraj2** [comment]
Can I work on this?

**Comment by PhoenixFlame101** [comment]
Sure, done.

**Comment by PhoenixFlame101** [comment]
@abhiraj2 any updates?

**Comment by abhiraj2** [comment]
yep almost done

**Comment by abhiraj2** [comment]
@PhoenixFlame101 PR open, check please
