### ISSUE TITLE
Creating and verifying a checksum file in a directory

### ISSUE THREAD

**Issue by PhoenixFlame101** [acmpesuecc/quickhash#4]
## The Problem

Add support to verify from and create checksum files.

## Possible Solutions

A checksum file is a plaintext file containing the checksums of all the files in a directory followed by the file name.

    Checksum format:
    2012b030c3f01589c399da291c57d803  NOTICE (notice the 2 spaces between the checksum and filename)

This feature should be triggered by passing in a CLI option `--create-checksum-file`. The program should calculate checksums for all the files in the root of the current working directory, and save it in a file `<algorithm>.checksum`. For example, an SHA-256 checksum will have the filename `sha256.checksum`.

There should also be support for the CLI option `--checksum-file` followed by a filepath, pointing to the checksum file for that directory. The algorithm should be automatically determined from the filename and all the filenames should be printed followed by a pass/fail result.

Examples:

    $ cargo run --create-checksum-file
    The file <alg>.checksum is located at <filepath>

    $ cargo run --checksum-file sha256.checksum
    NOTICE - Passed
    LICENSE - Passed
    README.md - Failed

## Testing

You can test the functionality by creating and validating the files using both functions. To create fail conditions on purpose, you can simply edit the file and see if it fails.

---
 - Block time: 45 mins (You need to give updates every 45 mins if you have been assigned)
 - Bounty points: 80

**Comment by abhiraj2** [comment]
If the other PR is accepted, can you assign me this?

**Comment by abhiraj2** [comment]
going well, have created all the flags necessary, now a bit of file manipulation is left

**Comment by abhiraj2** [comment]
Still going on, file management harder than I thought

**Comment by abhiraj2** [comment]
Had some progress

**Comment by abhiraj2** [comment]
@PhoenixFlame101 created PR
